[package]
name = "web_url"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs = { version = "0.10.0", features = ["classes", "properties", "loader"] }
ada-url = "3.3.0"
serde_json = "1.0.145"
utils = { path = "../utils" }
